### ISSUE TITLE
[fix] Local test failures on Node 24 — core Jest worker OOM and web route.test TS2576 NextResponse.json

### ISSUE THREAD

**Issue by brownm09** [merickvaughn/lifting-logbook#419]
## Symptom

Running `npm test` locally on Node 24 (Windows) against `origin/main` (commit `73f89a1`) produces the following pre-existing failures, unrelated to any code under test:

### packages/core — 6 suites OOM

```
FAIL tests/core/utils/parser/parseCycleDashboard.test.ts
FAIL tests/core/utils/jsUtil.test.ts
FAIL tests/core/services/workout/createGridV2.test.ts
FAIL tests/core/services/workout/updateLiftDates.test.ts
FAIL tests/core/services/bodyWeight.test.ts
FAIL tests/core/utils/import/validateLiftImport.test.ts
```

Each fails with:
```
Test suite failed to run
  Jest worker ran out of memory and crashed
    at ChildProcessWorker._onExit (../../node_modules/jest-worker/build/index.js:928:26)
```

Recurrence of the failure class previously fixed in #89 — appears to have regressed (or returned in a different form) under Node 24.

### apps/web — TS type errors in route handler tests

```
app/api/healthz/route.test.ts:65,66 — error TS2576:
  Property 'json' does not exist on type 'NextResponse<{ ok: boolean; }>'.
  Did you mean to access the static member 'NextResponse<{ ok: boolean; }>.json' instead?
```
Same class of error also surfaces in `app/livez/route.test.ts` and `lib/__tests__/programPlan.test.ts`.

This appears to be a `@types/next` / `next` type definition issue — `NextResponse` instances now disallow the instance `.json()` access these tests use.

## Suspected root cause

Local Node version is 24.13.0; CI runs Node 20 (per `.nvmrc`). The Node 24 caveat documented in [CLAUDE.md](https://github.com/brownm09/lifting-logbook/blob/main/CLAUDE.md) warns about install-time corruption but does not cover Jest worker memory pressure or `next` type drift under Node 24. CI is currently green for both packages, so this is a local-only failure mode at the moment.

## Why this matters

Blocks the pre-PR `npm test` gate for any local change. Currently being unblocked per CLAUDE.md failure-tracking rule by citing this issue in PR bodies.

## Acceptance criteria

- [ ] Identify whether Node 24 worker heap exhaustion is the root cause for the `packages/core` OOMs; if so, document the workaround (e.g., `--maxWorkers=2` or `NODE_OPTIONS=--max-old-space-size=4096`) or pin Jest config to handle it
- [ ] Investigate the `NextResponse.json` instance-vs-static-member type drift in the route handler tests; either update the test patterns or pin the relevant `@types/next` / `next` versions
- [ ] Confirm `npm test` passes locally on Node 24

## Workaround

Test suite passes in CI (Node 20). Local runs on Node 20 (`nvm use 20.11.1`) are expected to pass.

**Comment by brownm09** [comment]
## Update — Docker/Node 20 results

Ran `npm ci && npm test` inside `node:20.11.1-bullseye` (Docker for Windows) with the workspace bind-mounted, matching the `.nvmrc` pin.

### packages/core — **all 6 OOM failures gone**

```
Test Suites: 26 passed, 26 total
Tests:       160 passed, 160 total
Time:        71.36 s
```

Confirms the 6 `Jest worker ran out of memory and crashed` failures are a **Node 24 local environment issue**, not a code regression. The acceptance criterion to identify the root cause and document a workaround now narrows to: either pin local development to Node 20 (already encoded in `.nvmrc`) or, if Node 24 is desired locally, raise `NODE_OPTIONS=--max-old-space-size=4096` or `--maxWorkers=2`.

### apps/web — **still fails under Docker/Node 20.11.1, yet passes on CI**

`app/livez/route.test.ts` and `app/api/healthz/route.test.ts` fail with the same TS2339/TS2576 errors against `NextResponse` instance access. But CI (Ubuntu runner, `actions/setup-node@v4` resolving to Node 20.x.x — possibly a different patch version) passes the same tests on `origin/main` (run [26841253087](https://github.com/brownm09/lifting-logbook/actions/runs/26841253087)) and on PR #420's `Lint & Test` job.

So the second failure mode is **not** purely a Node 24 issue — it's a CI-vs-local-Docker resolution discrepancy at the `@types/next` / TypeScript layer. Hypotheses to investigate:
- CI image's Node patch (e.g., 20.18.x) ships a different `package.json` resolution than 20.11.1
- `node_modules/.cache` or `tsconfig.tsbuildinfo` in the local clone might be poisoning resolution
- Different `npm` version between the CI runner image and `node:20.11.1-bullseye`

Both failure classes are still tracked here; the apps/web class is broader than originally described (not Node-24-specific).
